### ISSUE TITLE
Add threatmodel directory if missing

### ISSUE THREAD

**Issue by Q-efx** [threatspec/threatspec#37]
If the threadmodel directory is missing during 

`threatspec run`

It will fail for a missing threats.json.

It should either auto-create the missing directory or warn that the directory should already exists.

**Comment by zeroXten** [comment]
Thanks. Will look into it, but struggling to find the time outside of work at the moment. PRs welcome ;)

**Comment by zeroXten** [comment]
I've replicated this, will look to fix in an update soon.

**Comment by zeroXten** [comment]
Fix merged to master, please retest.
