### ISSUE TITLE
Library files contain outdated components

### ISSUE THREAD

**Issue by DieserFelix** [threatspec/threatspec#4]
`threatspec run` appends to the various library files rather than recreating them each time. Therefore, components and connections remain even though the corresponding annotations have since been removed.

Subsequent runs of `threatspec report` then create rather confusing threat model diagrams

**Comment by zeroXten** [comment]
In theory, only the threats, controls, and components should persist across runs. This allows them to be identified in code and then used, reused and shared over time. The data in the threatmodel.yaml file should always be fresh and acts as the glue between the components, threats and controls.

Having said that... from a visualisation perspective... I think it is probably pulling in all threats, controls and components, regardless of whether they are referenced in the threatmodel.yaml. This is probably not the desired behaviour, so I'll take a look at the report generation.

**Comment by zeroXten** [comment]
Hey @DieserFelix. I've rewritten the whole reporting generation, so you should now only see components etc that are actively used in annotations.

**Comment by zeroXten** [comment]
Considering this fixed. Will reopen if needed.
